const Home = () => {
    
    return (
       <main className="home-main main-container">
           <h1>BIENVENUE SUR AMADOUFLIX</h1>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A, dolorem iste fugiat omnis. Quo, modi, autem, architecto, cum at nisi officia hic aspernatur natus cupiditate necessitatibus eveniet sunt perspiciatis vitae quidem repellendus doloribus nemo vero aperiam cumque aut mollitia soluta porro numquam tempora repudiandae quas quibusdam. Rerum, quod natus distinctio reiciendis explicabo. Aliquid, atque, vero vel ullam suscipit pariatur sequi blanditiis a unde facilis eius obcaecati praesentium reiciendis quo voluptate error repellendus distinctio optio possimus modi fugit repudiandae itaque architecto expedita magnam harum eaque voluptatum ducimus saepe voluptates! Rem, quidem, perferendis odit quasi fuga officia earum obcaecati modi sit ipsum.</p>
              <p>Corporis, reprehenderit corrupti quaerat saepe tempora? Aut, labore, voluptatum iste optio non ullam quis hic tempora rem minus earum expedita eos laboriosam dolorum saepe consequuntur et explicabo amet nihil impedit doloremque voluptate assumenda molestiae distinctio reprehenderit officia ipsam iure sequi modi id quae veniam reiciendis aliquam? Praesentium numquam vero minima cupiditate nobis quibusdam aut voluptatem eligendi dolorum tempora! Qui, fuga, mollitia eaque autem facere voluptatibus tempore provident dignissimos id eveniet ipsam consequatur voluptatum delectus quia obcaecati ea eius accusamus ex minima commodi nemo nisi impedit temporibus soluta sapiente sequi facilis nulla veritatis molestiae velit quam laudantium sint at. Tenetur, eligendi.</p>
              <p>Eaque, expedita facere officiis quod iste nobis nisi fugiat quos et sint doloribus soluta aliquam at ab sed saepe natus consectetur explicabo esse eveniet architecto facilis repellendus illum porro officia deserunt delectus temporibus provident iure pariatur optio laborum veniam impedit vitae animi vel quidem! Illo, id deleniti vitae quibusdam sunt architecto minima tempora provident dolorum optio fugit nisi facere commodi! Sequi, laborum sint est beatae voluptates dolores ullam dicta ut alias vitae? Ipsa, dolore, aliquid excepturi nisi maxime in est iure a consequatur unde nobis error sapiente iusto ipsum magni repellat minima quaerat incidunt adipisci libero quod aperiam odio. Itaque!</p>
              <p>Repudiandae, id alias nam quae harum beatae ab perspiciatis laborum amet aut in dolore doloribus repellendus fugiat dicta magnam illum cum distinctio suscipit molestiae illo eveniet sequi ex ad accusamus! Veritatis, itaque, molestiae, obcaecati, ipsam quisquam facere aliquid dicta totam vitae quis dolor eos error veniam impedit dolore ad ullam nisi laboriosam et inventore animi nam iusto magni! Facilis, cumque, nesciunt provident quibusdam veritatis natus temporibus suscipit porro vitae consectetur modi officiis iste fugiat inventore repellat necessitatibus autem sapiente nemo assumenda amet perspiciatis mollitia minus et minima quaerat maiores itaque velit laborum quas quae facere explicabo totam eveniet sint similique.</p>
              <p>Non, dignissimos, dolores, omnis, recusandae voluptatum doloremque exercitationem tempore repellat deleniti ipsam vel ut quibusdam officia nihil veritatis repellendus nesciunt. Dolores, accusamus, reiciendis, porro minima animi nisi rerum soluta quibusdam dicta veniam enim natus voluptate recusandae est excepturi doloremque provident? Esse, qui, deserunt quo consequuntur mollitia animi est vel fugit facere corporis? Voluptatem, explicabo, distinctio, incidunt dolorem doloremque perferendis et rem at vero esse praesentium dignissimos labore eveniet unde possimus. Deleniti, incidunt, quaerat, error, ea in consequuntur repellendus velit laboriosam quam cupiditate excepturi dolorem hic illum veritatis rerum soluta eius libero illo sunt nihil nam esse veniam dolores quod amet?</p>
              <p>Veniam, adipisci, eum, aliquid commodi ex culpa ducimus nobis eius modi accusantium fugiat dolores officiis nesciunt debitis ratione ipsum unde esse voluptatibus dolor possimus. Fugit, corporis, dolores, mollitia voluptates veniam natus tenetur laboriosam eaque dolore debitis temporibus magnam eius suscipit perspiciatis optio rerum qui non reprehenderit perferendis iusto nobis placeat quas fuga ratione vero! Voluptatum, necessitatibus, ullam id tenetur officiis vel dolorum sequi alias quaerat unde dolore molestiae maxime omnis rerum quae ipsam consectetur deleniti assumenda ratione aut tempore quo iusto consequuntur. Deserunt, omnis, autem, itaque, non voluptates adipisci repellat quidem tempora vel incidunt cum praesentium placeat mollitia illum architecto.</p>
              <p>Magni, maxime veritatis nihil porro a laboriosam. Quasi, necessitatibus, eaque, facere exercitationem tempora laboriosam eveniet rem nulla architecto ea distinctio eum accusantium modi! Dolore, fuga minima amet architecto sed totam. Non, mollitia, rem, dicta, rerum fuga voluptas facilis accusantium voluptate quod inventore maiores quam placeat facere eum fugiat. Animi, libero odit mollitia laboriosam eaque placeat at! Quod, voluptatum, aliquam doloribus voluptas eaque velit a aspernatur incidunt voluptates repellendus at unde dolorum eius autem culpa in repellat harum quisquam natus quos? Recusandae, deleniti, obcaecati, laboriosam, illum harum excepturi nostrum incidunt vero nemo impedit facere ad explicabo maxime perferendis eligendi at praesentium.</p>
       </main>
    )
}

export default Home